# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'untitleduSJXjP.ui'
##
## Created by: Qt User Interface Compiler version 6.9.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QComboBox, QLabel, QLineEdit,
    QMainWindow, QProgressBar, QPushButton, QSizePolicy,
    QTabWidget, QTextBrowser, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1000, 540)
        MainWindow.setStyleSheet(u"")
        MainWindow.setTabShape(QTabWidget.TabShape.Triangular)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.ConnectButton = QPushButton(self.centralwidget)
        self.ConnectButton.setObjectName(u"ConnectButton")
        self.ConnectButton.setGeometry(QRect(930, 20, 30, 30))
        self.ConnectButton.setStyleSheet(u"")
        self.textBrowser = QTextBrowser(self.centralwidget)
        self.textBrowser.setObjectName(u"textBrowser")
        self.textBrowser.setGeometry(QRect(20, 20, 771, 501))
        self.textBrowser.setStyleSheet(u"background-color: rgb(12, 12, 12);")
        self.textBrowser_2 = QTextBrowser(self.centralwidget)
        self.textBrowser_2.setObjectName(u"textBrowser_2")
        self.textBrowser_2.setGeometry(QRect(800, 60, 181, 61))
        self.textBrowser_2.setStyleSheet(u"background-color: rgb(12, 12, 12);")
        self.ConnectionLabel = QLabel(self.centralwidget)
        self.ConnectionLabel.setObjectName(u"ConnectionLabel")
        self.ConnectionLabel.setGeometry(QRect(820, 25, 101, 20))
        font = QFont()
        font.setFamilies([u"Cambria"])
        font.setPointSize(12)
        self.ConnectionLabel.setFont(font)
        self.textBrowser_3 = QTextBrowser(self.centralwidget)
        self.textBrowser_3.setObjectName(u"textBrowser_3")
        self.textBrowser_3.setGeometry(QRect(800, 140, 181, 141))
        self.textBrowser_3.setStyleSheet(u"background-color: rgb(12, 12, 12);")
        self.lineEdit = QLineEdit(self.centralwidget)
        self.lineEdit.setObjectName(u"lineEdit")
        self.lineEdit.setGeometry(QRect(40, 470, 730, 30))
        self.PortBox = QComboBox(self.centralwidget)
        self.PortBox.setObjectName(u"PortBox")
        self.PortBox.setGeometry(QRect(880, 80, 80, 24))
        self.ConnectionLabel_2 = QLabel(self.centralwidget)
        self.ConnectionLabel_2.setObjectName(u"ConnectionLabel_2")
        self.ConnectionLabel_2.setGeometry(QRect(830, 80, 31, 20))
        self.ConnectionLabel_2.setFont(font)
        self.Mculbl = QLabel(self.centralwidget)
        self.Mculbl.setObjectName(u"Mculbl")
        self.Mculbl.setGeometry(QRect(820, 160, 91, 16))
        self.portlbl = QLabel(self.centralwidget)
        self.portlbl.setObjectName(u"portlbl")
        self.portlbl.setGeometry(QRect(820, 190, 31, 16))
        self.memlbl = QLabel(self.centralwidget)
        self.memlbl.setObjectName(u"memlbl")
        self.memlbl.setGeometry(QRect(820, 220, 91, 16))
        self.spclbl = QLabel(self.centralwidget)
        self.spclbl.setObjectName(u"spclbl")
        self.spclbl.setGeometry(QRect(820, 250, 71, 16))
        self.label_5 = QLabel(self.centralwidget)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(820, 480, 49, 16))
        self.label_6 = QLabel(self.centralwidget)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(820, 500, 49, 16))
        self.label_7 = QLabel(self.centralwidget)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(820, 310, 71, 16))
        self.label_8 = QLabel(self.centralwidget)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(820, 400, 49, 16))
        self.label_9 = QLabel(self.centralwidget)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(820, 380, 71, 16))
        self.Mcuchn = QLabel(self.centralwidget)
        self.Mcuchn.setObjectName(u"Mcuchn")
        self.Mcuchn.setGeometry(QRect(910, 160, 51, 16))
        self.portchn = QLabel(self.centralwidget)
        self.portchn.setObjectName(u"portchn")
        self.portchn.setGeometry(QRect(860, 190, 51, 16))
        self.memchn = QLabel(self.centralwidget)
        self.memchn.setObjectName(u"memchn")
        self.memchn.setGeometry(QRect(910, 220, 51, 16))
        self.spcchn = QLabel(self.centralwidget)
        self.spcchn.setObjectName(u"spcchn")
        self.spcchn.setGeometry(QRect(900, 250, 71, 16))
        self.RamUsageChn = QProgressBar(self.centralwidget)
        self.RamUsageChn.setObjectName(u"RamUsageChn")
        self.RamUsageChn.setGeometry(QRect(840, 340, 118, 23))
        self.RamUsageChn.setValue(24)
        self.TempUsageChn = QProgressBar(self.centralwidget)
        self.TempUsageChn.setObjectName(u"TempUsageChn")
        self.TempUsageChn.setGeometry(QRect(840, 410, 118, 23))
        self.TempUsageChn.setValue(24)
        self.textBrowser_4 = QTextBrowser(self.centralwidget)
        self.textBrowser_4.setObjectName(u"textBrowser_4")
        self.textBrowser_4.setGeometry(QRect(800, 300, 181, 161))
        self.textBrowser_4.setStyleSheet(u"background-color: rgb(12, 12, 12);")
        self.time = QLabel(self.centralwidget)
        self.time.setObjectName(u"time")
        self.time.setGeometry(QRect(860, 480, 121, 16))
        self.date = QLabel(self.centralwidget)
        self.date.setObjectName(u"date")
        self.date.setGeometry(QRect(860, 500, 121, 16))
        self.textBrowser_5 = QTextBrowser(self.centralwidget)
        self.textBrowser_5.setObjectName(u"textBrowser_5")
        self.textBrowser_5.setGeometry(QRect(40, 40, 731, 421))
        MainWindow.setCentralWidget(self.centralwidget)
        self.textBrowser_4.raise_()
        self.ConnectButton.raise_()
        self.textBrowser.raise_()
        self.textBrowser_2.raise_()
        self.ConnectionLabel.raise_()
        self.textBrowser_3.raise_()
        self.lineEdit.raise_()
        self.PortBox.raise_()
        self.ConnectionLabel_2.raise_()
        self.Mculbl.raise_()
        self.portlbl.raise_()
        self.memlbl.raise_()
        self.spclbl.raise_()
        self.label_5.raise_()
        self.label_6.raise_()
        self.label_7.raise_()
        self.label_8.raise_()
        self.label_9.raise_()
        self.Mcuchn.raise_()
        self.portchn.raise_()
        self.memchn.raise_()
        self.spcchn.raise_()
        self.RamUsageChn.raise_()
        self.TempUsageChn.raise_()
        self.time.raise_()
        self.date.raise_()
        self.textBrowser_5.raise_()

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"RigourOS", None))
        self.ConnectButton.setText("")
        self.ConnectionLabel.setText(QCoreApplication.translate("MainWindow", u"Not Connected", None))
        self.ConnectionLabel_2.setText(QCoreApplication.translate("MainWindow", u"Port", None))
        self.Mculbl.setText(QCoreApplication.translate("MainWindow", u"Microcontroller :", None))
        self.portlbl.setText(QCoreApplication.translate("MainWindow", u"Port :", None))
        self.memlbl.setText(QCoreApplication.translate("MainWindow", u"Memory Used :", None))
        self.spclbl.setText(QCoreApplication.translate("MainWindow", u"Space Used :", None))
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"Time :", None))
        self.label_6.setText(QCoreApplication.translate("MainWindow", u"Date :", None))
        self.label_7.setText(QCoreApplication.translate("MainWindow", u"Ram Usage :", None))
        self.label_8.setText("")
        self.label_9.setText(QCoreApplication.translate("MainWindow", u"Temp Usage :", None))
        self.Mcuchn.setText("")
        self.portchn.setText("")
        self.memchn.setText("")
        self.spcchn.setText("")
        self.time.setText(QCoreApplication.translate("MainWindow", u"None", None))
        self.date.setText(QCoreApplication.translate("MainWindow", u"None", None))
    # retranslateUi

